---
title: "R Notebook"
output: html_notebook
---

**Packages**

```{r}
library(haven)
library(ggplot2)
library(dplyr)
library(gt)
library(plotly)
library(tidyr)
```

**Import ADAE**

```{r}
adae <- read_sas("https://github.com/elong0527/r4csr/raw/master/data-adam/adae.sas7bdat", 
    NULL)
View(adae)
```

**Import ADSL**

```{r}
adsl <- read_sas("https://github.com/elong0527/r4csr/raw/master/data-adam/adsl.sas7bdat", 
    NULL)
View(adsl)
```


**define functions used**

```{r}
fmt_num <- function(x, digits, width = digits + 4) {
  formatC(x,
    digits = digits,
    format = "f",
    width = width
  )
}
```

**Prep Data**

```{r}
pop <- adsl %>%
  filter(SAFFL == "Y") %>%
  rename(TRTAN = TRT01AN) %>%
  count(TRTAN, name = "tot")

pop

```

**tidy_ae**
```{r}

tidy_ae <- adae %>%
  mutate(
    all = SAFFL == "Y",
    drug = AEREL %in% c("POSSIBLE", "PROBABLE"),
    ser = AESER == "Y",
    drug_ser = drug & ser,
    die = AEOUT == "FATAL"
  ) %>%
  select(USUBJID, TRTAN, all, drug, ser, drug_ser, die) %>%
  pivot_longer(cols = c(all, drug, ser, drug_ser, die))

tidy_ae %>% head(4)
```


**We summarize the number and percentage of participants who meet each AE criteria.**
```{r}
ana <- tidy_ae %>%
  filter(value == TRUE) %>%
  group_by(TRTAN, name) %>%
  summarise(n = n_distinct(USUBJID)) %>%
  left_join(pop, by = "TRTAN") %>%
  mutate(
    pct = fmt_num(n / tot * 100, digits = 1),
    n = fmt_num(n, digits = 0),
    pct = paste0("(", pct, ")")
  )

ana %>% head(4)


```





**AE Data Viz**

```{r}
adae %>%
 filter(!(AEREL %in% "")) %>%
 ggplot() +
  aes(x = AESEV, fill = TRTA) +
  geom_bar() +
  scale_fill_hue(direction = 1) +
  theme_minimal()


```


```{r}
adae_update <- adae %>%
 filter(!(TRTA %in% "Xanomeline Low Dose")) %>%
 filter(!(AEREL %in% c("REMOTE", ""))) %>%
 filter(TRTEMFL %in% 
 "Y") 


```



Table

```{r}



```
